#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod attestation_resolver;
pub mod attester_resolver;
pub mod common;
pub mod context;
pub mod data_resolver;
pub mod eas;
pub mod ecdsa;
pub mod eip712;
pub mod eip712_proxy;
pub mod eip712_verifier;
pub mod erc20;
pub mod expiration_time_resolver;
pub mod i_schema_registry;
pub mod i_schema_resolver;
pub mod ieas;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod ierc20_permit;
pub mod math;
pub mod ownable;
pub mod paying_resolver;
pub mod permissioned_eip712_proxy;
pub mod recipient_resolver;
pub mod revocation_resolver;
pub mod safe_erc20;
pub mod schema_registry;
pub mod schema_resolver;
pub mod semver;
pub mod shared_types;
pub mod strings;
pub mod token_resolver;
pub mod value_resolver;
